//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hayvanlar
    {
        public int HayvanID { get; set; }
        public string HayvanTürü { get; set; }
        public string HayvanCinsi { get; set; }
        public string HayvanCinsiyeti { get; set; }
        public string HayvanYaşı { get; set; }
        public string HayvanSağlık { get; set; }
        public string HayvanBeslenme { get; set; }
        public string HayvanAşı { get; set; }
        public string HayvanAdres { get; set; }
    }
}
