//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yöneticiler
    {
        public int YöneticiID { get; set; }
        public string YöneticiAd { get; set; }
        public string YöneticiSoyad { get; set; }
        public string YöneticiBölüm { get; set; }
        public string YöneticiSifre { get; set; }
    }
}
